version: 2.1

orbs:
  node: circleci/node@4.7.0

# Define the jobs we want to run for this project
jobs:

  install:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - run:
          command: npm install

  lint:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - run: npm run lint

  prettier:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run prettier

  jest:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run jest

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - install
      - jest:
          requires:
            - install
      - lint:
          requires:
            - install
      - prettier:
          requires:
            - install
