version: 2.1

orbs:
  node: circleci/node@4.7.0

# Define the jobs we want to run for this project
jobs:
  install:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: cimg/node:17.1.0

    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run prettier

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - jest:
          requires:
            - install
      - lint:
          requires:
            - install
      - prettier:
          requires:
            - install
      - build:
          requires:
            - prettier
            - jest
            - lint
